project/apps/user_profile/urls.py
"""
Apps auth endpoints.
"""
from django.contrib.auth import views
from django.urls import path, include
from django.views.generic import TemplateView

from .views import Register, BasePageView, UploadCSVView, ProfileView, UploadXMLView

urlpatterns = [
    path('', BasePageView.as_view(), name='base'),
    path('register/', Register.as_view(), name='register'),
    path('auth/', include('django.contrib.auth.urls')),
    path('upload_csv/', UploadCSVView.as_view(), name='upload_csv'),
    path('upload_xml/', UploadXMLView.as_view(), name='upload_xml'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile')
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('', include('project.apps.user_profile.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/user_profile/models.py
"""
This module contains all models for db
"""
from django.contrib.auth.models import User
from django.db.models import Model, OneToOneField, CASCADE, ImageField, CharField, TextField
from django.db.models.signals import post_save
from django.dispatch import receiver


def path_to_img(instance, filename):
    return f"avatar_user/avatar{instance.user}){filename[-4:]}"


class UserProfile(Model):
    user = OneToOneField(User, related_name='profile', on_delete=CASCADE)
    avatar_urls = TextField(max_length=1000)
    avatar = ImageField(upload_to=path_to_img)

    def __str__(self):
        return str(self.user.username)

    class Meta:
        """
        Change name model in admin panel.
        """

        verbose_name = "User Profile"
        verbose_name_plural = 'User Profile'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

project/apps/user_profile/forms.py
"""
Creation of forms for registration, user authorization
"""
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import (
    UserCreationForm as DjangoUserCreationForm,
    AuthenticationForm as DjangoAuthenticationForm,
)
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserCreationForm(DjangoUserCreationForm):
    """
    New user registration form.
    """
    username = forms.CharField(
        label=_("Username"),
        max_length=20,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    first_name = forms.CharField(
        label=_("First name"),
        max_length=20,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    last_name = forms.CharField(
        label=_("Last name"),
        max_length=20,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta(DjangoUserCreationForm.Meta):
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2',
        ]


class AuthenticationForm(DjangoAuthenticationForm):
    """
    Base user form for auth.
    """

    def clean(self):
        """
        The function takes values from the form and checks
         its validity and the existence of a user with such data.
        """

        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(
                self.request,
                username=username,
                password=password,
            )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class UploadCSVDataForm(forms.Form):
    csv_file = forms.FileField(widget=forms.FileInput(attrs={'accept': ".csv", 'multiple': True}))

class UploadXMLDataForm(forms.Form):
    xml_file = forms.FileField(widget=forms.FileInput(attrs={'accept': ".xml", 'multiple': True}))

project/apps/user_profile/views.py
"""
This module contains all views.
"""
import csv

from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import DetailView, ListView, FormView

from .forms import UserCreationForm, AuthenticationForm, UploadCSVDataForm, UploadXMLDataForm
from .models import UserProfile
from .utils import check_save_data_csv, check_save_data_xml


class Register(View):
    """
    Views for new user registration.
    """
    template_name = 'registration/register.html'

    def get(self, request):
        """
        Base method for views registration.
        """
        context = {
            'form': UserCreationForm(),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        """
        Registration method with data validation and subsequent sending of a message to the mail.
        """
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            login_user =authenticate(username=username, password=password)
            login(request, login_user)
            return redirect('base')
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


class ProfileView(DetailView):
    """
    User profile views.
    """
    model = UserProfile
    context_object_name = 'profile'
    template_name = 'profile.html'


class MyLoginView(LoginView):  # pylint: disable=too-many-ancestors
    """
    Login views.
    """
    form_class = AuthenticationForm


class BasePageView(ListView):
    def get(self, request, *args, **kwargs):
        users = UserProfile.objects.all()
        context = {
            'profiles': users
        }
        return render(request, 'base.html', context)


class UploadCSVView(FormView):
    template_name = 'upload_csv.html'

    def get(self, request, **kwargs):
        context = {
            'form': UploadCSVDataForm(),
        }
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        form = UploadCSVDataForm(request.POST, request.FILES)

        if not form.is_valid():
            return render(request, self.template_name, {'form': UploadCSVDataForm})
        check_save_data_csv(csv.DictReader(request.FILES['csv_file'].read().decode('utf-8').splitlines()))

        return redirect('base')


class UploadXMLView(FormView):
    template_name = 'upload_xml.html'

    def get(self, request, **kwargs):
        context = {
            'form': UploadXMLDataForm(),
        }
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        form = UploadXMLDataForm(request.POST, request.FILES)

        if not form.is_valid():
            return render(request, self.template_name, {'form': UploadXMLDataForm})

        check_save_data_xml(request.FILES['xml_file'])
        return redirect('base')

project/apps/user_profile/templates/profile.html
{% extends 'base.html' %}

{% block title %}<title>Профиль {{ profile.username }}</title>{% endblock title %}

{% block content %}
    {% if user.is_superuser %}
        <section style="background-color: #eee;">
            <div class="container py-5">

                <div class="row">
                    <div class="col-lg-4">
                        <div class="card mb-4">
                            <div class="card-body text-center">
                                {% if profile.avatar %}
                                    <picture>
                                        <img class="card-img-top"
                                             src="{{ profile.avatar.url }}"
                                             alt=""/>
                                    </picture>
                                {% elif profile.avatar_urls %}
                                    <picture>
                                        <img class="card-img-top"
                                             src={{ profile.avatar_urls }}
                                                     alt=""/>
                                    </picture>
                                {% else %}
                                    <picture>
                                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp"
                                             alt="avatar"
                                             class="rounded-circle img-fluid" style="width: 150px;">
                                    </picture>
                                {% endif %}
                                <h5 class="my-3">{{ profile.user.first_name }} {{ profile.user.last_name }}</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="card mb-4">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <p class="mb-0">Username</p>
                                    </div>
                                    <div class="col-sm-9">
                                        <p class="text-muted mb-0">{{ profile.user.username }}</p>
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <p class="mb-0">Full name</p>
                                    </div>
                                    <div class="col-sm-9">
                                        <p class="text-muted mb-0">{{ profile.user.first_name }} {{ profile.user.last_name }}</p>
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <p class="mb-0">Email</p>
                                    </div>
                                    <div class="col-sm-9">
                                        <p class="text-muted mb-0">{{ profile.user.email }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>
    {% else %}
        <meta http-equiv="refresh" content="0; URL={% url 'base' %}">
    {% endif %}
{% endblock content %}

project/apps/user_profile/templates/upload_csv.html
{% extends 'base.html' %}

{% block content %}
    <section class="vh-50 bg-image mt-5 mb-5">
        <div class="mask d-flex align-items-center gradient-custom-3">
            <div class="container">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div class="card" style="border-radius: 15px;">
                            <div class="card-body p-5">
                                <h2 class="text-uppercase text-center mb-5">Upload CSV file</h2>


                                <form action="{% url 'upload_csv' %}" method="post" enctype="multipart/form-data">

                                    {% if form.errors %}
                                        {% for field in form %}
                                            {% for error in field.errors %}
                                                <div class="alert alert-danger">
                                                    <strong>{{ error|escape }}</strong>
                                                </div>
                                            {% endfor %}
                                        {% endfor %}
                                        {% for error in form.non_field_errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                    {% csrf_token %}

                                    <label class="custom-uploader" for="file">Upload Your File</label>
                                    <input name="csv_file" type="file" accept=".csv" required="" id="id_csv_file"/>
                                    <button class="btn btn-success" name="submit" type="submit"> Upload File
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

project/apps/user_profile/templates/upload_xml.html
{% extends 'base.html' %}

{% block content %}
    <section class="vh-50 bg-image mt-5 mb-5">
        <div class="mask d-flex align-items-center gradient-custom-3">
            <div class="container">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div class="card" style="border-radius: 15px;">
                            <div class="card-body p-5">
                                <h2 class="text-uppercase text-center mb-5">Upload XML file</h2>


                                <form action="{% url 'upload_xml' %}" method="post" enctype="multipart/form-data">

                                    {% if form.errors %}
                                        {% for field in form %}
                                            {% for error in field.errors %}
                                                <div class="alert alert-danger">
                                                    <strong>{{ error|escape }}</strong>
                                                </div>
                                            {% endfor %}
                                        {% endfor %}
                                        {% for error in form.non_field_errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                    {% csrf_token %}

                                    <label class="custom-uploader" for="file">Upload Your File</label>
                                <input name="xml_file" type="file" accept=".xml" required="" id="id_xml_file"/>
                                    <button class="btn btn-success" name="submit" type="submit"> Upload File
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

project/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    {% load static %}
</head>
<body style="margin: 0; min-height: 100%; grid-template-rows: auto 1fr auto; display:flex; flex-direction:column;justify-content: space-between;">
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'base' %}" class="btn btn-outline-light me-2">Home</a></li>
                {% if user.is_superuser %}
                    <li><a href="{% url 'upload_csv' %}" class="btn btn-outline-light me-2">Upload CSV Data</a></li>
                    <li><a href="{% url 'upload_xml' %}" class="btn btn-outline-light me-2">Upload XML Data</a></li>
                {% endif %}
            </ul>

            <div class="text-end">
                {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}" class="btn btn-warning">logout</a>
                {% else %}
                    <a href="{% url 'login' %}" class="btn btn-outline-light me-2">Login</a>
                    <a href="{% url 'register' %}" class="btn btn-warning">Registration</a>
                {% endif %}

            </div>
        </div>
    </div>
</header>
{% block content %}
    {% if user.is_authenticated %}
        {% if user.is_superuser %}
            <section class="py-5">
                <div class="container px-4 px-lg-5 mt-5">
                    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                        {% for users in profiles %}
                            <div class="col-xl-3 col-lg-3 col-md-5 col-sm-8 col-8" style="margin-bottom: 20px;">
                                <a class="tag-a-custom" href="{% url 'profile' pk=users.id %}"
                                   style="text-decoration: none;">
                                    <div class="card h-100">
                                        {% if users.avatar %}
                                            <picture>
                                                <img class="card-img-top"
                                                     src="{{ users.avatar.url }}"
                                                     alt=""/>
                                                {% elif users.avatar_urls %}

                                                <source srcset={{ users.avatar_urls.url }}>
                                                <img class="card-img-top"
                                                     src={{ users.avatar_urls }}
                                                             alt=""/>
                                            </picture>
                                        {% else %}
                                        {% endif %}

                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">{{ users.user.username }}</li>
                                            <li class="list-group-item">{{ users.user.first_name }}</li>
                                            <li class="list-group-item">{{ users.user.last_name }}</li>
                                        </ul>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
        {% else %}
            <section class="vh-50 bg-image mt-5 mb-5">
                <div class="mask d-flex align-items-center h-100 gradient-custom-3">
                    <div class="container h-40">
                        <div class="row d-flex justify-content-center align-items-center h-100">
                            <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                                <div class="card" style="border-radius: 15px;">
                                    <div class="card-body p-5">

                                        <h3 class="text-center mb-5" style="margin-top: 3rem;">Only the administrator
                                            can see the information here</h3>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        {% endif %}
    {% else %}
        <section class="vh-50 bg-image mt-5 mb-5">
            <div class="mask d-flex align-items-center h-100 gradient-custom-3">
                <div class="container h-40">
                    <div class="row d-flex justify-content-center align-items-center h-100">
                        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                            <div class="card" style="border-radius: 15px;">
                                <div class="card-body p-5">

                                    <h3 class="text-center mb-5" style="margin-top: 3rem;">You need to register.</h3>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    {% endif %}
{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
        integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
        crossorigin="anonymous"></script>
</body>
</html>